### ISSUE TITLE
Automatic calculations

### ISSUE THREAD

**Issue by Nikki-Valentine** [CalfloraDB/BugReports#13]
Hey, I have noticed a handful of records that had 0 plants given were not automatically calculated to percent cover and infested area. I thought this was automatically calculated, but these seem to be exceptions.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/nikki/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/nikki/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Root | ID | Taxon | Date | Group | # Plants | % Cover | Gross Area (m2) | Infested Area (m2) | Mgmt Status
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
wb1848-290 | mg147202 | Cynara cardunculus | 8/6/2021 | OC-CA State Parks-Orange Coast Weed Warriors | 0 | 0 | 1 |   | searched for but not found
wb1848-319 | po89566 | Cynara cardunculus | 5/17/2018 | OC-CA State Parks-Orange Coast Weed Warriors | 0 | 0 |   |   | searched for but not found
wb1845-177 | mg147210 | Cynara cardunculus | 8/6/2021 | OC-CA State Parks-Orange Coast Weed Warriors | 0 | 0 | 1.3 |   | searched for but not found
po89579 | mg132496 | Cynara cardunculus | 4/23/2021 | OC-CA State Parks-Orange Coast Weed Warriors | 0 | 0 | 28.27 |   | searched for but not found
wb2157-2 | mg130858 | Ehrharta calycina | 4/8/2021 | OC-CA State Parks-Orange Coast Weed Warriors | 0 |   | 28.27 |   | searched for but not found
wb2157-26 | mg131135 | Ehrharta calycina | 4/12/2021 | Orange County Parks Plantopia | 0 |   | 886.26156 |   | searched for but not found
wb2157-27 | mg163743 | Ehrharta calycina | 5/5/2022 | Orange County Parks Plantopia | 0 |   |   |   | searched for but not found
wb2157-27 | mg131133 | Ehrharta calycina | 4/12/2021 | Orange County Parks Plantopia | 0 |   | 2140.78705 |   | searched for but not found

</body>

</html>

**Comment by Nikki-Valentine** [comment]
Also, I am not sure if this is automatically linked, but I found entries that had percent treated>0, that did not have their management status updated to "under management."

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/nikki/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/nikki/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Root | ID | Taxon | Date | # Plants | % Cover | Gross Area (m2) | Infested Area (m2) | Mgmt Status | % Treated
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | po192066 | Cynara cardunculus | 5/20/2021 | 30 |   | 17303.9 |   |   | 33
po196965 | po235499 | Centaurea diluta | 6/2/2022 | 11000 | 92.2 | 843.2 | 777.5 | verified | 100
po196965 | pow3604 | Centaurea diluta | 3/23/2022 | 4000 | 33.5 | 843.2 | 282.7 | verified | 100
po76809 | pow3920 | Cynara cardunculus | 4/13/2022 | 85 | 0.2 | 32139.2 | 66.8 | verified | 100
  | pow3508 | Glebionis coronaria | 3/16/2022 | 2500 | 5 to 25 | 19.63 | 19.63 |   | 100
wb1842-14 | mg131964 | Ehrharta calycina | 4/20/2021 | 8 | 0 - 1 | 28.27 |   | under management | 0



</body>

</html>

**Comment by palflora** [comment]
I was testing out Net Area auto-calculation on the Orange County Parks form. I created observations in OP, made a polygon and entered a percent cover, then uploaded and checked in My Observations.

My first attempt resulted in the value "square meters" being where the auto-calculated number should be.

My second attempt worked as expected and net area was auto-calculated.

**Comment by Calflora** [comment]
There are two issues here:
1. Management status not being set to "under management" when percent treated has a value.
2. Infested Area not being set when a. there is a polygon and b. there is a value for percent cover.
Both issues have been fixed by modifying server code, and tested on Android OP.
