### ISSUE TITLE
Exact number of plants entered registering as "Other..."

### ISSUE THREAD

**Issue by matthewmajor** [CalfloraDB/BugReports#14]
![image](https://github.com/CalfloraDB/BugReports/assets/129779127/9fca6f7c-d4d3-4041-93f1-aa6dbef6bf47)
[Calflora Plant Count Issue August 2023.pdf](https://github.com/CalfloraDB/BugReports/files/12373488/Calflora.Plant.Count.Issue.August.2023.pdf)
[Mail - Major, Matt - Outlook.pdf](https://github.com/CalfloraDB/BugReports/files/12373489/Mail.-.Major.Matt.-.Outlook.pdf)

**Comment by edorrington** [comment]
Hi @matthewmajor, I see the issue. I'll try to replicate and get back to you. Would you happen to know, in any of the cases where the value was replaced with "Other...", what the value entered was? Thanks.

**Comment by edorrington** [comment]
@Calflora, the way it works now, in a field that has an "Other..." option, if you choose Other..., but don't enter any value (or if for some reason the system thinks there's no value) it substitutes the text "Other...". But we should think about whether that's the best option, or if it should substitute 0 if otherType is number, or an empty string, etc.

**Comment by matthewmajor** [comment]
![image](https://github.com/CalfloraDB/BugReports/assets/129779127/0fac99c0-6756-4d27-83a4-3edef431714f)

**Comment by matthewmajor** [comment]
@Calflora @edorrington Hi, any update on this? Thanks.

**Comment by edorrington** [comment]
Hi @matthewmajor , I'm still trying to replicate it locally. The question is whether it's the app that is not sending the "Other" data, or if it's something on the server side. I'll let you know if I can replicate it...
Thanks for the reminder!

**Comment by matthewmajor** [comment]
![image](https://github.com/CalfloraDB/BugReports/assets/129779127/96977fda-f053-46be-92fd-c456d0b1ea57)

**Comment by matthewmajor** [comment]
Hi Ed, at the OC Calflora training today other people are reporting that when they use the "Other" field for number of plants and enter a specific number, it is not recorded in the system. Two other people in different groups (State Parks, NBC) reported this issue. Any update on troubleshooting?

**Comment by palflora** [comment]
Confirming this was happening at the training. I have notes for the fields "plant count" and "habitat" doing this. Though it seemed to be certain people having this issue, others reported it working for them. @matthewmajor do you know if people are actually having it happen intermittently? Or the people that it happens to it always happens?

I was also told people have resorted to taking screen shots of their records before saving them to keep records of this data. So this tells us that they are certainly entering the values in the fields and not leaving them empty by accident.

**Comment by matthewmajor** [comment]
![image](https://github.com/CalfloraDB/BugReports/assets/129779127/59b7f702-16a8-42cf-ac6a-4ab7ad03eb1e)

**Comment by edorrington** [comment]
I have finally been able to replicate this issue thanks to another user's report. I can replicate it always if I edit the observation before uploading it. With that information, I have been able to locate where the problem is occurring in the code, and will have a fix for it out with the next release, 1.9.3, which should be out at the beginning of next week.
