### ISSUE TITLE
Calflora homepage is garbled and inaccessible

### ISSUE THREAD

**Issue by matthewmajor** [CalfloraDB/BugReports#15]
I cannot log in or access any of the applications. The homepage imagery is missing or garbled. 

![image](https://github.com/CalfloraDB/BugReports/assets/129779127/975c03a6-7d34-41d6-84a9-0627eace56a0)

**Comment by edorrington** [comment]
Hi @matthewmajor, thanks for reporting. We've removed it from the home page for now.

**Comment by edorrington** [comment]
It's fixed now
