### ISSUE TITLE
GO and MGS not working

### ISSUE THREAD

**Issue by matthewmajor** [CalfloraDB/BugReports#16]
Yesterday not working. Still not working this morning.

![image](https://github.com/CalfloraDB/BugReports/assets/129779127/35651b83-015d-4ccc-bf50-9bf55f596c17)

![image](https://github.com/CalfloraDB/BugReports/assets/129779127/bfebb384-f654-4b84-993b-1f294e5507f3)

**Comment by matthewmajor** [comment]
Update: I signed out and back in and didn't work. I restarted my cpu and signed in again and it is working now.

**Comment by edorrington** [comment]
Thanks, @matthewmajor. Most likely a transient issue between the server and your browser.
