### ISSUE TITLE
Can't move records between projects

### ISSUE THREAD

**Issue by matthewmajor** [CalfloraDB/BugReports#17]
I am trying to move records from an Archive project into an Active Project but I am getting the following error:

![image](https://github.com/CalfloraDB/BugReports/assets/129779127/35066f41-a799-4e21-8f95-4324bd4a4f46)

**Comment by mkbowler** [comment]
I get the same error when I try to move my own select records (a group of 160 records) to a different project, within the same group.

**Comment by Calflora** [comment]
This is fixed in Multiple Group Search v 1.37.7
