### ISSUE TITLE
Cannot use spreadsheet edit function to change records

### ISSUE THREAD

**Issue by mkbowler** [CalfloraDB/BugReports#18]
Using the spreadsheet EDIT function (in MGS) does not change the field value. I need to move some records to a different project and tried to use the spreadsheet EDIT. It tells me how many records I changed, I click on Save, and it comes back and says records updated. But when I refresh the page, the old value is still there, nothing has changed. It says it has saved the changes but actually has not. I am a project czar.

<img width="1120" alt="Screenshot 2023-11-15 144807" src="https://github.com/CalfloraDB/BugReports/assets/129778765/f3b3f5bc-8a11-42a5-9b13-57ccebac25a3">
<img width="1120" alt="Screenshot 2023-11-15 144902" src="https://github.com/CalfloraDB/BugReports/assets/129778765/3ad05dba-2d17-4286-ad96-2c7571ae1289">
<img width="1120" alt="Screenshot 2023-11-15 144939" src="https://github.com/CalfloraDB/BugReports/assets/129778765/516f66db-bee7-4504-ba7c-858b2c9b9069">

**Comment by Calflora** [comment]
If you want to change the project using the MGS spreadsheet, use the field "Project #" instead of "Project".

**Comment by mkbowler** [comment]
Thanks John.
