### ISSUE TITLE
Ghost records in OP using iOS

### ISSUE THREAD

**Issue by matthewmajor** [CalfloraDB/BugReports#19]
At a Calflora coordination meeting today this issue was raised as an ongoing problem for iOS. I haven't experienced it myself because I use Android. Apparently records are uploaded, disappear from the iOS device, and then they show up again on the iOS device at a later date. This may be leading to the duplication of records which is obviously a problem for accurately tracking data. Amanda Swanson, Alisa Flint, and Alys Arenas all mentioned this issue.

**Comment by edorrington** [comment]
This issue has been fixed and will be rolled out in the next Observer Pro release, 1.9.3, which should be available at the beginning of next week.
