### ISSUE TITLE
Batch edit convert units error

### ISSUE THREAD

**Issue by matthewmajor** [CalfloraDB/BugReports#21]
Hi, I used batch edit to change infested area and gross area from square meters to acres. The result of this change is riddled with errors, and I'm not sure what to do. Please advise.

https://www.calflora.org/entry/mgo.html#srch=t&taxon=Ehrharta+calycina&gps=140&pcount=x&hfil=R&rid=rx9195&smpy=t&urp=t&smth=X

![image](https://github.com/CalfloraDB/BugReports/assets/129779127/b85ee2e4-c5fb-4e43-9adf-eb1e1aa483a2)

**Comment by Calflora** [comment]
Batch convert from square meters to acres is working properly today.
