### ISSUE TITLE
Map aerial images not loading

### ISSUE THREAD

**Issue by matthewmajor** [CalfloraDB/BugReports#22]
I am unable to load detailed imagery in both Multiple Group Search and POE. Aerial background imagery is obscured by grey tiles with the text "Sorry we have no imagery here."

![image](https://github.com/CalfloraDB/BugReports/assets/129779127/b473b51a-d670-4538-8782-9d245e3df553)

**Comment by matthewmajor** [comment]
Shapes are also 1) not saving, and 2) not loading comprehensively. The system is not reliable at the moment so I will need to stop working in WM and will try again tomorrow. 

![image](https://github.com/CalfloraDB/BugReports/assets/129779127/651e0fb4-d4db-4824-b93e-d8f8e92bc550)

**Comment by edorrington** [comment]
Hi @matthewmajor the map images not showing up points to a networking issue on your end (those images are all coming directly from Google, rather than from Calflora, so if they're not showing up, unless Google is down, it's most likely a networking issue. Is it still going on?

**Comment by matthewmajor** [comment]
Hi @edorrington - our internal countywide network was having issues yesterday so I think you're right. Thanks for replying.
