### ISSUE TITLE
Can't access records (of others)

### ISSUE THREAD

**Issue by matthewmajor** [CalfloraDB/BugReports#23]
I'm trying to open records in the group that I am a czar of. Error messages. See photos.

![image](https://github.com/CalfloraDB/BugReports/assets/129779127/5fb64005-34b0-4ead-bc45-f45a85628f0c)

![image](https://github.com/CalfloraDB/BugReports/assets/129779127/d7461860-4fa2-47e4-a6e5-2257112235ec)

![image](https://github.com/CalfloraDB/BugReports/assets/129779127/ef87add2-a7cb-402e-8d44-18f3d4791649)

**Comment by edorrington** [comment]
Hi @matthewmajor that's a VERY odd error. If you look at the URL in those images, it's as though the editor button was picking up the HTML of the photo as the ID of the record. Do you by any chance have any unusual browser extensions running on this computer & browser? Also, which column set are you using there? Is it an existing one, or a custom one that you set up?

**Comment by matthewmajor** [comment]
Hi @edorrington - this is a custom column set I created on the fly to be able to quickly see photos associated with multiple records. I'm using Chrome and I have the following browser extensions: Smartsheet, Paperpile, and 1Password.

**Comment by Calflora** [comment]
@matthewmajor Matt,
If you change the column set so that the ID is in the first column,
it will work. Multiple Group Search at the moment assumes that
ID is the first column.
