### ISSUE TITLE
Singleton is not showing up on MGS search

### ISSUE THREAD

**Issue by matthewmajor** [CalfloraDB/BugReports#24]
During the course of cleaning up records and history stacking I discovered that a singleton record is not showing up. I have the history filter set to "Only the most recent" so I see only one point/polygon per stack. When I change the history filter to "All records", the singleton shows up! The singleton should show up with both searches. I don't understand why this isn't working properly. 

Here's the singleton: 
https://www.calflora.org/entry/poe.html#vrid=mg114279

Here's the MGS with "Only the most recent":
https://www.calflora.org/entry/mgo.html#srch=t&taxon=Pennisetum+setaceum&gps=140&inma=t&y=33.5542&x=-117.7765&z=17&pcount=x&hfil=R&cset=d&smpy=t&urp=t&smth=X
![image](https://github.com/CalfloraDB/BugReports/assets/129779127/bce5dd2a-53bd-44ce-b9a8-909f81ac78c4)

Here's the MGS with "All records":
https://www.calflora.org/entry/mgo.html#srch=t&taxon=Pennisetum+setaceum&gps=140&inma=t&y=33.5542&x=-117.7765&z=17&pcount=x&cset=d&smpy=t&urp=t&smth=X
![image](https://github.com/CalfloraDB/BugReports/assets/129779127/345a95b1-ddfc-4665-b1d1-3e36203c51bc)

**Comment by Calflora** [comment]
It is showing up now.
