### ISSUE TITLE
Ghost polygons showing up in some searches and not others

### ISSUE THREAD

**Issue by matthewmajor** [CalfloraDB/BugReports#25]
An MGS search with the history filter set to "All records" shows a certain set of points and polygons. With "Only the most recent" and "use reference polygon" selected, a different set of polygons show up, including a big polygon that didn't show up using "All records". This doesn't make sense to me since all records (and therefore all polygons) should show up with an "All records" search.  

MGS with "All records":
https://www.calflora.org/entry/mgo.html#srch=t&taxon=Pennisetum+setaceum&gps=140&pcount=x&cset=d&rid=rx9169&smpy=t&smth=X&srname=ROCA+Pennisetum+setaceum&srid=4565
![image](https://github.com/CalfloraDB/BugReports/assets/129779127/c5f5c07c-4c60-4994-aced-32aa2c949891)

MGS with "Only the most recent" and "use reference polygon":
https://www.calflora.org/entry/mgo.html#srch=t&taxon=Pennisetum+setaceum&gps=140&pcount=x&hfil=R&cset=d&rid=rx9169&smpy=t&urp=t&smth=X
![image](https://github.com/CalfloraDB/BugReports/assets/129779127/f6d0c149-ce58-4b35-9b43-321ad0008eec)

**Comment by Calflora** [comment]
It looks like the application did not clear all polygons from the first search.
