### ISSUE TITLE
The hour information of deleted Record still left in the work section database

### ISSUE THREAD

**Issue by IRCGIS** [CalfloraDB/BugReports#26]
Record deleted but the hours information still left in the work section database.
For example https://www.calflora.org/entry/poe.html#vrid=pow4362 has been deleted
But you can still find that record in work session: https://www.calflora.org/entry/sentry2.html#search=t&who=black&group=139&before=2023-1-18&after=2023-1-18

Note: the "Hours" Column in the Group Observations show total Person Hours (Work Session) not total hours (# People x Person Hours).

**Comment by Calflora** [comment]
Associated hours records are deleted when an observation is deleted. Something must have gone wrong in this case.

**Comment by IRCGIS** [comment]
Is there a quick way to find those records and deleted them? I found around 15 records in 2023.
