### ISSUE TITLE
Endless Updating Cycle-Android Observer Pro

### ISSUE THREAD

**Issue by Jecoffey35** [CalfloraDB/BugReports#3]
I've noticed this problem in the past month-can't sign in to CalFlora Observer Pro with my Pixel3a or my work android trimble unit-after sign in, updating process occurs successfully, then prompts sign in. I sign in again, prompts update, which is successful...etc.

**Comment by Calflora** [comment]
Can you provide any error messages from the phone?

**Comment by Jecoffey35** [comment]
Hmmm this happened so long ago, I think it's probably fine now.

Thanks!
