### ISSUE TITLE
What is the best way for people to find this website and participate?

### ISSUE THREAD

**Issue by matthewmajor** [CalfloraDB/BugReports#5]
What is the best way to find the Calflora dashboard on Github?
Is there a link on the Calflora website that directs to this website?

**Comment by Calflora** [comment]
There is a link at the top of the NEWS page:
https://calflora.org/entry/applications2.html

There is also a link on the Weed Manager page under Resources:
https://www.calflora.org/entry/weed-mgr.html#resources
