### ISSUE TITLE
Polygon and Location Point Edits on Calfora Website Not Saving

### ISSUE THREAD

**Issue by alysarenas** [CalfloraDB/BugReports#6]
Hello! When I edit polygons and location points on my computer, they don't always save. Leaving two examples below:

- https://www.calflora.org/entry/poe.html#vrid=io80838 - I have moved/edited this polygon and changed the Location Point and hit saved multiple times. Still reverts to what was captured in the field on my iPhone.
- https://www.calflora.org/entry/poe.html#vrid=io82554 - I have fixed this polygon multiple times, still reverting to what was captured in the field on my iPhone.

I've noticed this happened to multiple observations. It's not clear why some edits to entries have saved and other have not...any suggestions or help on how to fix this would be appreciated. Thank you! -Alys

**Comment by matthewmajor** [comment]
I have had the same issue a few times. I have also noticed that if I change the population priority (1,2,3, etc.) for a record/stack, sometimes it will not save even if I have used the proper workflow. Could these two issues be related?

**Comment by Calflora** [comment]
We have not been able to duplicate this problem.
