### ISSUE TITLE
Search option for records with "no priority"

### ISSUE THREAD

**Issue by mkbowler** [CalfloraDB/BugReports#7]
It would be useful to be able to search for population records that do not have a set priority. Current search options are for "any priority" or a specific priority (1, 2, 3, …), but if I'm trying to set priorities for a bunch of records, I'd rather know which ones don't already have a priority set.

**Comment by Calflora** [comment]
This is available in Group Observations v. 2.87.5,
and in Multiple Group Search v. 1.37.6.

If you select Priority Ranking = "none", it will return all records with an empty priority raanking.
