### ISSUE TITLE
Separate treatment / assessment records

### ISSUE THREAD

**Issue by mkbowler** [CalfloraDB/BugReports#8]
I would like to see the treatment records be a separate record type from assessment records. This would allow me to directly enter treatment metrics (# of plants pulled, net area treated, and a polygon of the treated area), as opposed to using % treated (which requires an assessment for for each treatment plus offline calculations to get to # pulled, net treated area, etc.). 

In my operations I typically first do an assessment of the area, then follow with multiple treatments over the next few days or weeks. Having to enter a new assessment for each treatment event is time consuming and not needed if the population is not changing over the treatment time period. With separate treatment records there would be an initial assessment followed by treatment records, and then a final assessment or assessments.

I do see an option separate treatment polygon types, but no info on how to use.

**Comment by Calflora** [comment]
We could modify the data collection form you are now using,
and add a switch at the top. If you set the switch to "assessment",
then all of the assessment fields would appear. 
If you set the switch to "treatment", then all of the treatment fields would appear.

**Comment by mkbowler** [comment]
Thanks John. That would work if we added more fields to the treatment data, which will require a broader discussion with the various stakeholders. Leave this one closed until we've had that discussion, whenever it occurs.
